# a, b = map(int, input().split())
# print(a + b)
# print(a - b)
# print(a * b)
# print(a // b)
# print(a % b)

# a, b, c = map(int, input().split())
# print((a + b) % c)
# print(((a % c) + (b % c)) % c)
# print((a * b) % c)
# print(((a % c) * (b % c)) % c)

a = int(input())
b = int(input())
c = a * (b % 10)
d = a * ((b % 100) // 10)
e = a * (b // 100)
f = c + (d * 10) + (e * 100)
print(c)
print(d)
print(e)
print(f)